name: zhp.pl docker image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: zhpadmin
        password: ${{ secrets.DOCKERHUB_TOKEN }}

# TODO improve caching in Dockerfile and use github cache to speed up build: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
# possibly, we could wait for this to be implemented: https://github.com/docker/buildx/pull/535
    - name: Build docker
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: |
          gkzhp/zhp-pl:latest
          gkzhp/zhp-pl:${{ github.sha	}}

# TODO prepare docker-compose with the specified tag (git SHA) and env name. Choose proper env file in docker

# TODO deploy the docker image,
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   if: success() && github.ref == 'refs/heads/master'
  #   needs: build
  #   steps:
  #   - name: Download package
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: App